#! /bin/sh

if [ -z "$srcdir" ] ; then
    srcdir=.
fi

. $srcdir/common.sh

rm -f "$TESTHOME/d/new"
echo data | client put "d/new" && \
    [ -r "$TESTHOME/d/new" ] && grep data "$TESTHOME/d/new" > /dev/null



