.\" COPYRIGHT AND PERMISSION NOTICE
.\"
.\" Copyright (C) 1999 J.H.M. Dassen (Ray) <jdassen@wi.LeidenUniv.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are 
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a 
.\" permission notice identical to this one.
.\"
.\" Permission is granted to copy and distribute translations of this manual
.\" into another language, under the above conditions for modified versions,
.\" except that this permission notice may be stated in a translation approved
.\" by the Free Software Foundation, Inc. <URL:http://www.fsf.org>
.\"
.\" END COPYRIGHT AND PERMISSION NOTICE
.\"
.\" If you make modified versions of this manual, please notify the current 
.\" maintainers of the package you received this manual from and make your
.\" modified versions available to them.
.\"
.TH LSH-MAKE-SEED 1 "NOVEMBER 2004" LSH-MAKE-SEED "Lsh Manuals"
.SH NAME
lsh-make-seed \- Creates random seed file for the
.B YARROW 
pseudorandomnessgenerator.
.SH SYNOPSIS
.B lsh-make-seed
[\fIOPTION\fR...]

.SH DESCRIPTION
.B CAUTION! The information in this manpage may be invalid or outdated. For authorative
.B information on lsh, please see it's Texinfo manual (see the
.I SEE\ ALSO
.B section).

Creates an initial random seed file for the 
.B YARROW
pseudorandomnessgenerator used by lsh.


.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrite any existing seed file.
.HP
\fB\-o\fR, \fB\-\-output\-file\fR=\fIFilename\fR Default is ~/.lsh/seed-file
.TP
\fB\-\-server\fR
Save seed file where the lshd server expects it
.TP
\fB\-\-sloppy\fR
Generate seed file even if we can't collect a good
amount of randomness from the environment.
.TP
\fB\-\-debug\fR
Print huge amounts of debug information
.TP
\fB\-\-log\-file\fR=\fIFile\fR name
Append messages to this file.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress all warnings and diagnostic messages
.TP
\fB\-\-trace\fR
Detailed trace
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose diagnostic messages
.TP
-?, \fB\-\-help\fR
Give this help list
.TP
\fB\-\-usage\fR
Give a short usage message
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version
.PP
Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.

.SH DIAGNOSTICS
See the 
.B --log-file
,
.B --verbose
,
.B --trace
and 
.B --debug
options.

.SH "REPORTING BUGS"
Report bugs to <bug-lsh@gnu.org>.




.SH COPYING
The lsh suite of programs is distributed under the GNU General Public
License; see the COPYING and AUTHORS files in the source distribution for
details.
.SH AUTHOR
The lsh program suite is written mainly by Niels M\[:o]ller <nisse@lysator.liu.se>.

This man-page was written for lsh 2.0 by Pontus Freyhult
<pont_lsh@soua.net>, it is based on a template written by
J.H.M. Dassen (Ray) <jdassen@wi.LeidenUniv.nl>.

.SH "SEE ALSO"
.BR DSA (5),
.BR lsh (1),
.BR lsh-authorize (1),
.BR lsh-decode-key (1),
.BR lsh-decrypt-key (1),
.BR lsh-export-key (1),
.BR lsh-keygen (1),
.BR lsh-upgrade (1),
.BR lsh-upgrade-key (1),
.BR lsh-writekey (1),
.BR lshd (8),
.BR secsh (5),
.BR SHA (5),
.BR SPKI (5),
.BR ssh-conv (1)

The full documentation for
.B lsh
is maintained as a Texinfo manual.  If the
.B info
and
.B lsh
programs are properly installed at your site, the command
.IP
.B info lsh
.PP
should give you access to the complete manual.
