.\" COPYRIGHT AND PERMISSION NOTICE
.\"
.\" Copyright (C) 1999 J.H.M. Dassen (Ray) <jdassen@wi.LeidenUniv.nl>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are 
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a 
.\" permission notice identical to this one.
.\"
.\" Permission is granted to copy and distribute translations of this manual
.\" into another language, under the above conditions for modified versions,
.\" except that this permission notice may be stated in a translation approved
.\" by the Free Software Foundation, Inc. <URL:http://www.fsf.org>
.\"
.\" END COPYRIGHT AND PERMISSION NOTICE
.\"
.\" If you make modified versions of this manual, please notify the current 
.\" maintainers of the package you received this manual from and make your
.\" modified versions available to them.
.\"
.TH LSH-AUTHORIZE 1 "NOVEMBER 2004" LSH-AUTHORIZE "Lsh Manuals"
.SH NAME
lsh-authroize \- secsh (SSH2) client
.SH SYNOPSIS
.B lsh-authorize KEY-FILE

.SH DESCRIPTION
.B CAUTION! The information in this manpage may be invalid or outdated. For authorative
.B information on lsh, please see it's Texinfo manual (see the
.I SEE\ ALSO
.B section).

Authorizes public key login for the key corresponding to the public
key contained in KEY-FILE.

.SH FILES

Authorized keys are stored under 

.B
$HOME/.lsh/authorized_keys_sha1/

the file name is currently the SHA1 hash of the public key, but this may change in
the future.

.SH "REPORTING BUGS"
Report bugs to <bug-lsh@gnu.org>.


.SH COPYING
The lsh suite of programs is distributed under the GNU General Public
License; see the COPYING and AUTHORS files in the source distribution for
details.
.SH AUTHOR
The lsh program suite is written mainly by Niels M\[:o]ller <nisse@lysator.liu.se>.

This man-page was written for lsh 2.0 by Pontus Freyhult
<pont_lsh@soua.net>, it is based on a template written by
J.H.M. Dassen (Ray) <jdassen@wi.LeidenUniv.nl>.


.SH "SEE ALSO"
.BR lsftp (1),
.BR lshg (1),
.BR lsh-authorize (1),
.BR lsh-keygen (1),
.BR lsh-make-seed (1),
.BR lsh-upgrade (1),
.BR lsh-upgrade-key (1),
.BR lsh-writekey (1),
.BR lshd (8),
.BR ssh-conv (1)

The full documentation for
.B lsh
is maintained as a Texinfo manual.  If the
.B info
and
.B lsh
programs are properly installed at your site, the command
.IP
.B info lsh
.PP
should give you access to the complete manual.
