#! /bin/sh

# Tests the key generation programs

echo Testing lsh-keygen RSA key generation 

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

rm -f foo foo.pub
../lsh-keygen -a rsa -l 777 | ../lsh-writekey -c none -o foo \
  && "$SEXP_CONV" < foo && [ -s foo -a -s foo.pub ] && test_success

test_done
