#! /bin/sh

echo lsh, test 8, unencrypted session

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

LSHD_FLAGS="$LSHD_FLAGS --crypto=none"
LSH_FLAGS="$LSH_FLAGS --crypto=none"

spawn_lshd && run_lsh "exit 0" && test_success

test_done
