#! /bin/sh

if [ -z "$srcdir" ] ; then
  srcdir="`pwd`"
fi

. $srcdir/functions.sh

# Create home directory for tests
rm -rf "$TEST_HOME"
mkdir "$TEST_HOME"

HOME="$TEST_HOME"
export HOME

echo "Creating seed file"
../lsh-make-seed -q --sloppy

echo "Creating identity.pub for tests"
../lsh-keygen -a dsa -l2 | ../lsh-writekey -c none

echo "Authorizing key for login"
"$srcdir/../lsh-authorize" "$HOME/.lsh/identity.pub"

test_success
