#! /bin/sh

# Tests the key generation programs

echo Testing lsh-writekey

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

rm -f foo foo.pub
../lsh-writekey -c none -o foo < $srcdir/key-1.private && [ -s foo -a -s foo.pub ] && test_success

test_done
